[package]
name = "utxorpc-ledger"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "^1.4"
pbjson = "^0.5"
pbjson-types = "^0.5"
prost = "^0.11"
serde = "^1.0"

[features]
default = []
## @@protoc_insertion_point(features)
